name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            artifact_name: bb-whatsapp-pod-linux-amd64
          - os: linux
            arch: arm64
            artifact_name: bb-whatsapp-pod-linux-arm64
          - os: darwin
            arch: amd64
            artifact_name: bb-whatsapp-pod-darwin-amd64
          - os: darwin
            arch: arm64
            artifact_name: bb-whatsapp-pod-darwin-arm64
          - os: windows
            arch: amd64
            artifact_name: bb-whatsapp-pod-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -v -o ${{ matrix.artifact_name }} ./cmd/bb-whatsapp-pod

      - name: Generate pod.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cat > pod.json << EOF
          {
            "pod": {
              "name": "bb-whatsapp-pod",
              "version": "${VERSION}",
              "description": "A Babashka pod for interacting with WhatsApp",
              "platforms": {
                "linux/amd64": {
                  "binary": "bb-whatsapp-pod-linux-amd64"
                },
                "linux/arm64": {
                  "binary": "bb-whatsapp-pod-linux-arm64"
                },
                "darwin/amd64": {
                  "binary": "bb-whatsapp-pod-darwin-amd64"
                },
                "darwin/arm64": {
                  "binary": "bb-whatsapp-pod-darwin-arm64"
                },
                "windows/amd64": {
                  "binary": "bb-whatsapp-pod-windows-amd64.exe"
                }
              }
            }
          }
          EOF

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_name }}
            pod.json
          if-no-files-found: error
          retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: List files
        run: ls -R

      - name: Move artifacts to root
        run: |
          mkdir -p release
          find . -type f -name "bb-whatsapp-pod-*" -exec mv {} release/ \;
          find . -type f -name "pod.json" -exec mv {} release/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 